import {signal} from '@angular/core'
import {
  TrainingExerciseHistoryEntry,
  TrainingScheduleCatalogDraftItem,
} from '@areas/llimbro/training/models/training.models'

export function createTrainingStoreStub() {
  const selectedDate = signal(new Date(2026, 7, 3))
  const selectedScheduleId = signal<number | null>(5)
  const schedules = signal([{
    id: 5,
    id_user: 'test-user',
    portable_id: '11111111-1111-4111-8111-111111111111',
    name: 'Horario 1',
    is_active: true,
    source_share_id: null,
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
  }])
  const scheduleItems = signal([{
    id: 10,
    id_user: 'test-user',
    schedule_id: 5,
    exercise_id: 1,
    weekday: 1,
    set_count: 3,
    target_repetitions: 10,
    target_weight_kg: 40,
    sort_order: 0,
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
    training_exercise: {id: 1, name: 'Sentadilla'},
  }])
  const exercise = {
      id: 1,
      id_user: 'test-user',
      name: 'Sentadilla',
      portable_id: '22222222-2222-4222-8222-222222222222',
      description: 'Patrón dominante de rodilla',
      tips: ['Mantén el torso firme'],
      image_path: null,
      video_url: 'https://example.com/squat',
      training_modalities: ['strength'],
      muscle_groups: ['quadriceps'],
      movement_patterns: ['squat'],
      archived_at: null,
      created_at: '2026-08-01T00:00:00Z',
      updated_at: '2026-08-01T00:00:00Z',
    }
  const exerciseHistory = [{
    id: 20,
    id_user: 'test-user',
    exercise_id: 1,
    performed_on: '2026-08-03',
    sort_order: 0,
    created_at: '2026-08-03T00:00:00Z',
    updated_at: '2026-08-03T00:00:00Z',
    training_set: [{
      id: 30,
      id_user: 'test-user',
      entry_id: 20,
      position: 1,
      repetitions: 10,
      weight_kg: 40,
      created_at: '2026-08-03T00:00:00Z',
      updated_at: '2026-08-03T00:00:00Z',
    }],
  }]
  const previousSessions = signal<ReadonlyMap<number, TrainingExerciseHistoryEntry | null>>(new Map([[1, {
    ...exerciseHistory[0],
    id: 19,
    performed_on: '2026-07-27',
    training_set: [
      {...exerciseHistory[0].training_set[0], id: 29, entry_id: 19, position: 1},
      {...exerciseHistory[0].training_set[0], id: 28, entry_id: 19, position: 2, repetitions: null, weight_kg: null},
    ],
  }]]))
  const recentSessions = signal<ReadonlyMap<number, readonly TrainingExerciseHistoryEntry[]>>(new Map([[1, [
    previousSessions().get(1)!,
    {
      ...exerciseHistory[0],
      id: 18,
      performed_on: '2026-07-20',
      training_set: [
        {...exerciseHistory[0].training_set[0], id: 27, entry_id: 18, position: 1},
      ],
    },
  ]]]))
  return {
    exercises: signal([exercise]),
    exerciseDetail: signal(exercise),
    exerciseHistory: signal(exerciseHistory),
    exerciseDetailError: signal<string | null>(null),
    schedules,
    selectedScheduleId,
    selectedSchedule: signal(schedules()[0]),
    activeSchedule: signal(schedules()[0]),
    selectedScheduleItems: scheduleItems,
    schedule: scheduleItems,
    shares: signal([]),
    entries: signal([{
      id: 20,
      id_user: 'test-user',
      exercise_id: 1,
      performed_on: '2026-08-03',
      sort_order: 0,
      created_at: '2026-08-03T00:00:00Z',
      updated_at: '2026-08-03T00:00:00Z',
      training_exercise: {id: 1, name: 'Sentadilla'},
      training_set: [{
        id: 30,
        id_user: 'test-user',
        entry_id: 20,
        position: 1,
        repetitions: 10,
        weight_kg: 40,
        created_at: '2026-08-03T00:00:00Z',
        updated_at: '2026-08-03T00:00:00Z',
      }],
    }]),
    previousSessions,
    recentSessions,
    selectedDate,
    loadingExercises: signal(false),
    loadingSchedule: signal(false),
    loadingEntries: signal(false),
    loadingExerciseDetail: signal(false),
    savingSchedule: signal(false),
    savingScheduleCatalog: signal(false),
    savingEntries: signal(false),
    savingExercise: signal(false),
    savingExerciseImage: signal(false),
    sharing: signal(false),
    loadExercises: async () => undefined,
    loadSchedule: async () => undefined,
    loadEntries: async () => undefined,
    loadPreviousSessions: async (_exerciseIds: readonly number[]) => undefined,
    loadExerciseDetail: async () => undefined,
    saveScheduleDay: async () => undefined,
    saveScheduleCatalog: async (
      _drafts: readonly TrainingScheduleCatalogDraftItem[],
      _selectedKey: string,
    ) => undefined,
    createSchedule: async () => undefined,
    renameSelectedSchedule: async () => undefined,
    duplicateSelectedSchedule: async () => undefined,
    activateSelectedSchedule: async () => undefined,
    deleteSelectedSchedule: async () => undefined,
    selectSchedule: (id: number) => selectedScheduleId.set(id),
    shareExercises: async () => ({id: 'share-id', token: 'share-token'}),
    shareSelectedSchedule: async () => ({id: 'share-id', token: 'share-token'}),
    revokeShare: async () => undefined,
    saveEntries: async () => undefined,
    archiveExercise: async () => undefined,
    selectDate: (date: Date) => selectedDate.set(date),
  }
}
