begin;

create schema nocendland;
create schema nocendland_private;

revoke all on schema nocendland from public, anon, authenticated, service_role;
revoke all on schema nocendland_private from public, anon, authenticated, service_role;
grant usage on schema nocendland to authenticated, service_role;

create type nocendland.nutrition_objetive_levels as enum ('keep', 'good', 'top');

create table nocendland."user" (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  email text not null,
  user_name text not null,
  avatar_url text not null,
  constraint user_id_fkey foreign key (id) references auth.users(id)
    on update cascade on delete cascade
);

comment on table nocendland."user" is
  'Tabla intermedia de usuarios para tener localizada la información de los usuarios que se necesita.';

create table nocendland.nutrition_ingredient (
  id bigint generated by default as identity primary key,
  id_user uuid not null,
  name text not null,
  calories_per_100 bigint,
  proteins_per_100 double precision,
  fats_per_100 double precision,
  carbohydrates_per_100 double precision,
  description text,
  grams_per_unit smallint,
  image_route text,
  constraint nutrition_ingredient_id_user_fkey foreign key (id_user)
    references nocendland."user"(id),
  constraint nutrition_ingredient_calories_range
    check (calories_per_100 between 0 and 1000),
  constraint nutrition_ingredient_proteins_range
    check (proteins_per_100 between 0 and 100),
  constraint nutrition_ingredient_fats_range
    check (fats_per_100 between 0 and 100),
  constraint nutrition_ingredient_carbohydrates_range
    check (carbohydrates_per_100 between 0 and 100),
  constraint nutrition_ingredient_grams_per_unit_range
    check (grams_per_unit between 0 and 32767)
);

comment on column nocendland.nutrition_ingredient.image_route is
  'Ruta de la imagen en el bucket';

create table nocendland.nutrition_intake (
  id bigint generated by default as identity primary key,
  ingredient bigint not null,
  quantity_in_grams bigint default 0,
  id_user uuid not null,
  date date not null default now(),
  units smallint,
  constraint nutrition_intake_id_user_foreign foreign key (id_user)
    references nocendland."user"(id),
  constraint nutrition_intake_ingredient_fkey foreign key (ingredient)
    references nocendland.nutrition_ingredient(id) on delete cascade,
  constraint nutrition_intake_quantity_range
    check (quantity_in_grams between 0 and 100000),
  constraint nutrition_intake_units_range
    check (units between 0 and 10000)
);

comment on column nocendland.nutrition_intake.units is
  'Aquí se guardan las unidades del intake. Puede ser null, en ese caso no se hará el calculo';

create table nocendland.nutrition_objective (
  proteins double precision not null default 0,
  carbohydrates double precision not null default 0,
  fats double precision not null default 0,
  calories bigint not null default 0,
  level nocendland.nutrition_objetive_levels not null,
  id_user uuid not null,
  constraint nutrition_objective_pkey primary key (level, id_user),
  constraint nutrition_objective_id_user_fkey foreign key (id_user)
    references nocendland."user"(id) on update cascade on delete cascade
);

create table nocendland.nutrition_objetive_level (
  id bigint generated by default as identity primary key,
  level nocendland.nutrition_objetive_levels not null default 'keep',
  id_user uuid not null,
  constraint nutrition_objetive_level_level_check check (level::text = ''::text),
  constraint nutrition_objetive_level_id_user_foreign foreign key (id_user)
    references nocendland."user"(id)
);

create table nocendland.training_exercise (
  id bigint generated by default as identity primary key,
  id_user uuid not null,
  name text not null,
  description text,
  tips text[] not null default '{}'::text[],
  image_path text,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  portable_id uuid not null default gen_random_uuid(),
  video_url text,
  training_modalities text[] not null default '{}'::text[],
  muscle_groups text[] not null default '{}'::text[],
  movement_patterns text[] not null default '{}'::text[],
  constraint training_exercise_id_user_fkey foreign key (id_user)
    references nocendland."user"(id) on delete cascade,
  constraint training_exercise_id_id_user_key unique (id, id_user),
  constraint training_exercise_owner_portable_key unique (id_user, portable_id),
  constraint training_exercise_name_check check (btrim(name) <> ''),
  constraint training_exercise_video_url_check check (
    video_url is null or video_url ~* '^https://[^[:space:]]+$'
  ),
  constraint training_exercise_modalities_check check (
    training_modalities <@ array[
      'strength', 'cardio', 'power_plyometrics', 'mobility', 'flexibility', 'balance_stability'
    ]::text[]
  ),
  constraint training_exercise_muscle_groups_check check (
    muscle_groups <@ array[
      'full_body', 'chest', 'back', 'shoulders', 'biceps', 'triceps', 'forearms_grip',
      'core_abs', 'glutes_hips', 'quadriceps', 'hamstrings', 'calves'
    ]::text[]
  ),
  constraint training_exercise_movement_patterns_check check (
    movement_patterns <@ array[
      'push', 'pull', 'squat', 'hip_hinge', 'lunge_unilateral', 'rotation',
      'anti_rotation_core_stability', 'loaded_carry', 'locomotion', 'jump', 'isolation'
    ]::text[]
  )
);

create table nocendland.training_share (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references nocendland."user"(id) on delete cascade,
  token_hash text not null unique,
  share_type text not null,
  title text not null,
  manifest jsonb not null,
  created_at timestamptz not null default now(),
  revoked_at timestamptz,
  constraint training_share_type_check check (share_type in ('exercises', 'schedule')),
  constraint training_share_title_check check (btrim(title) <> ''),
  constraint training_share_token_hash_check check (token_hash ~ '^[0-9a-f]{64}$'),
  constraint training_share_manifest_check check (
    manifest ->> 'version' = 'training-share/v1'
    and manifest ->> 'type' = share_type
    and jsonb_typeof(manifest -> 'exercises') = 'array'
  )
);

create table nocendland.training_schedule (
  id bigint generated by default as identity primary key,
  id_user uuid not null references nocendland."user"(id) on delete cascade,
  portable_id uuid not null default gen_random_uuid(),
  name text not null,
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  source_share_id uuid references nocendland.training_share(id) on delete set null,
  constraint training_schedule_name_check check (btrim(name) <> ''),
  constraint training_schedule_id_owner_key unique (id, id_user),
  constraint training_schedule_owner_portable_key unique (id_user, portable_id)
);

create table nocendland.training_schedule_item (
  id bigint generated by default as identity primary key,
  id_user uuid not null references nocendland."user"(id) on delete cascade,
  exercise_id bigint not null,
  weekday smallint not null,
  set_count smallint not null default 1,
  target_repetitions smallint,
  target_weight_kg numeric,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  schedule_id bigint not null,
  constraint training_schedule_item_id_id_user_key unique (id, id_user),
  constraint training_schedule_item_schedule_owner_fkey
    foreign key (schedule_id, id_user)
    references nocendland.training_schedule(id, id_user) on delete cascade,
  constraint training_schedule_item_exercise_owner_fkey
    foreign key (exercise_id, id_user)
    references nocendland.training_exercise(id, id_user) on delete cascade,
  constraint training_schedule_item_schedule_weekday_exercise_key
    unique (schedule_id, weekday, exercise_id),
  constraint training_schedule_item_weekday_check check (weekday between 1 and 7),
  constraint training_schedule_item_set_count_check check (set_count >= 1),
  constraint training_schedule_item_target_repetitions_check
    check (target_repetitions is null or target_repetitions >= 0),
  constraint training_schedule_item_target_weight_kg_check
    check (target_weight_kg is null or target_weight_kg >= 0),
  constraint training_schedule_item_sort_order_check check (sort_order >= 0)
);

create table nocendland.training_entry (
  id bigint generated by default as identity primary key,
  id_user uuid not null references nocendland."user"(id) on delete cascade,
  exercise_id bigint not null,
  performed_on date not null default current_date,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint training_entry_id_id_user_key unique (id, id_user),
  constraint training_entry_exercise_owner_fkey
    foreign key (exercise_id, id_user)
    references nocendland.training_exercise(id, id_user) on delete restrict,
  constraint training_entry_id_user_performed_on_exercise_id_key
    unique (id_user, performed_on, exercise_id),
  constraint training_entry_sort_order_check check (sort_order >= 0)
);

create table nocendland.training_set (
  id bigint generated by default as identity primary key,
  id_user uuid not null references nocendland."user"(id) on delete cascade,
  entry_id bigint not null,
  position smallint not null,
  repetitions smallint,
  weight_kg numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint training_set_entry_owner_fkey
    foreign key (entry_id, id_user)
    references nocendland.training_entry(id, id_user) on delete cascade,
  constraint training_set_entry_id_position_key unique (entry_id, position),
  constraint training_set_position_check check (position >= 1),
  constraint training_set_repetitions_check check (repetitions is null or repetitions >= 0),
  constraint training_set_weight_kg_check check (weight_kg is null or weight_kg >= 0)
);

create or replace view nocendland.nutrition_intake_with_totals
with (security_invoker = true)
as
select
  intake.id as intake_id,
  intake.ingredient,
  intake.quantity_in_grams,
  ingredient.name as ingredient_name,
  (
    ingredient.calories_per_100::numeric
      * intake.quantity_in_grams::numeric
      / 100::numeric
  )::bigint as calories,
  ingredient.proteins_per_100 * intake.quantity_in_grams::double precision
    / 100::double precision as proteins,
  ingredient.fats_per_100 * intake.quantity_in_grams::double precision
    / 100::double precision as fats,
  ingredient.carbohydrates_per_100 * intake.quantity_in_grams::double precision
    / 100::double precision as carbohydrates,
  intake.date,
  intake.id_user
from nocendland.nutrition_intake intake
join nocendland.nutrition_ingredient ingredient on intake.ingredient = ingredient.id;

create or replace view nocendland.nutrition_objectives_totals
with (security_invoker = true)
as
select
  sum(intake.calories) as calories,
  sum(intake.proteins) as proteins,
  sum(intake.fats) as fats,
  sum(intake.carbohydrates) as carbohydrates,
  intake.date,
  intake.id_user
from nocendland.nutrition_intake_with_totals intake
group by intake.date, intake.id_user;

create index nutrition_ingredient_user_idx
  on nocendland.nutrition_ingredient (id_user);
create index nutrition_intake_user_idx
  on nocendland.nutrition_intake (id_user);
create index nutrition_intake_ingredient_idx
  on nocendland.nutrition_intake (ingredient);
create index nutrition_objective_user_idx
  on nocendland.nutrition_objective (id_user);
create index nutrition_objetive_level_user_idx
  on nocendland.nutrition_objetive_level (id_user);
create index training_exercise_user_idx
  on nocendland.training_exercise (id_user);
create unique index training_exercise_active_name_unique
  on nocendland.training_exercise (id_user, lower(btrim(name)))
  where archived_at is null;
create index training_schedule_source_share_idx
  on nocendland.training_schedule (id_user, source_share_id)
  where source_share_id is not null;
create index training_schedule_source_share_fk_idx
  on nocendland.training_schedule (source_share_id)
  where source_share_id is not null;
create unique index training_schedule_owner_name_key
  on nocendland.training_schedule (id_user, lower(btrim(name)));
create unique index training_schedule_one_active_per_owner_key
  on nocendland.training_schedule (id_user)
  where is_active;
create index training_schedule_item_user_idx
  on nocendland.training_schedule_item (id_user);
create index training_schedule_item_schedule_order_idx
  on nocendland.training_schedule_item (schedule_id, weekday, sort_order);
create index training_schedule_item_schedule_owner_idx
  on nocendland.training_schedule_item (schedule_id, id_user);
create index training_schedule_item_exercise_owner_idx
  on nocendland.training_schedule_item (exercise_id, id_user);
create index training_entry_user_idx
  on nocendland.training_entry (id_user);
create index training_entry_exercise_owner_idx
  on nocendland.training_entry (exercise_id, id_user);
create index training_set_user_idx
  on nocendland.training_set (id_user);
create index training_set_entry_owner_idx
  on nocendland.training_set (entry_id, id_user);
create index training_share_owner_idx
  on nocendland.training_share (owner_id);

alter table nocendland."user" enable row level security;
alter table nocendland.nutrition_ingredient enable row level security;
alter table nocendland.nutrition_intake enable row level security;
alter table nocendland.nutrition_objective enable row level security;
alter table nocendland.nutrition_objetive_level enable row level security;
alter table nocendland.training_exercise enable row level security;
alter table nocendland.training_share enable row level security;
alter table nocendland.training_schedule enable row level security;
alter table nocendland.training_schedule_item enable row level security;
alter table nocendland.training_entry enable row level security;
alter table nocendland.training_set enable row level security;

create policy user_select_own on nocendland."user"
  for select to authenticated using ((select auth.uid()) = id);
create policy user_insert_own on nocendland."user"
  for insert to authenticated with check ((select auth.uid()) = id);
create policy user_update_own on nocendland."user"
  for update to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

create policy nutrition_ingredient_select_own on nocendland.nutrition_ingredient
  for select to authenticated using ((select auth.uid()) = id_user);
create policy nutrition_ingredient_insert_own on nocendland.nutrition_ingredient
  for insert to authenticated with check ((select auth.uid()) = id_user);
create policy nutrition_ingredient_update_own on nocendland.nutrition_ingredient
  for update to authenticated
  using ((select auth.uid()) = id_user)
  with check ((select auth.uid()) = id_user);
create policy nutrition_ingredient_delete_own on nocendland.nutrition_ingredient
  for delete to authenticated using ((select auth.uid()) = id_user);

create policy nutrition_intake_select_own on nocendland.nutrition_intake
  for select to authenticated using ((select auth.uid()) = id_user);
create policy nutrition_intake_insert_own on nocendland.nutrition_intake
  for insert to authenticated with check ((select auth.uid()) = id_user);
create policy nutrition_intake_update_own on nocendland.nutrition_intake
  for update to authenticated
  using ((select auth.uid()) = id_user)
  with check ((select auth.uid()) = id_user);
create policy nutrition_intake_delete_own on nocendland.nutrition_intake
  for delete to authenticated using ((select auth.uid()) = id_user);

create policy nutrition_objective_select_own on nocendland.nutrition_objective
  for select to authenticated using ((select auth.uid()) = id_user);
create policy nutrition_objective_insert_own on nocendland.nutrition_objective
  for insert to authenticated with check ((select auth.uid()) = id_user);
create policy nutrition_objective_update_own on nocendland.nutrition_objective
  for update to authenticated
  using ((select auth.uid()) = id_user)
  with check ((select auth.uid()) = id_user);
create policy nutrition_objective_delete_own on nocendland.nutrition_objective
  for delete to authenticated using ((select auth.uid()) = id_user);

create policy nutrition_objetive_level_no_client_access
  on nocendland.nutrition_objetive_level
  for all to anon, authenticated
  using (false)
  with check (false);

create policy training_exercise_select_own on nocendland.training_exercise
  for select to authenticated using ((select auth.uid()) = id_user);
create policy training_exercise_insert_own on nocendland.training_exercise
  for insert to authenticated with check ((select auth.uid()) = id_user);
create policy training_exercise_update_own on nocendland.training_exercise
  for update to authenticated
  using ((select auth.uid()) = id_user)
  with check ((select auth.uid()) = id_user);
create policy training_exercise_delete_own on nocendland.training_exercise
  for delete to authenticated using ((select auth.uid()) = id_user);

create policy training_schedule_select_own on nocendland.training_schedule
  for select to authenticated using ((select auth.uid()) = id_user);
create policy training_schedule_insert_own on nocendland.training_schedule
  for insert to authenticated with check ((select auth.uid()) = id_user);
create policy training_schedule_update_own on nocendland.training_schedule
  for update to authenticated
  using ((select auth.uid()) = id_user)
  with check ((select auth.uid()) = id_user);
create policy training_schedule_delete_own on nocendland.training_schedule
  for delete to authenticated using ((select auth.uid()) = id_user);

create policy training_schedule_item_select_own on nocendland.training_schedule_item
  for select to authenticated using ((select auth.uid()) = id_user);
create policy training_schedule_item_insert_own on nocendland.training_schedule_item
  for insert to authenticated with check ((select auth.uid()) = id_user);
create policy training_schedule_item_update_own on nocendland.training_schedule_item
  for update to authenticated
  using ((select auth.uid()) = id_user)
  with check ((select auth.uid()) = id_user);
create policy training_schedule_item_delete_own on nocendland.training_schedule_item
  for delete to authenticated using ((select auth.uid()) = id_user);

create policy training_entry_select_own on nocendland.training_entry
  for select to authenticated using ((select auth.uid()) = id_user);
create policy training_entry_insert_own on nocendland.training_entry
  for insert to authenticated with check ((select auth.uid()) = id_user);
create policy training_entry_update_own on nocendland.training_entry
  for update to authenticated
  using ((select auth.uid()) = id_user)
  with check ((select auth.uid()) = id_user);
create policy training_entry_delete_own on nocendland.training_entry
  for delete to authenticated using ((select auth.uid()) = id_user);

create policy training_set_select_own on nocendland.training_set
  for select to authenticated using ((select auth.uid()) = id_user);
create policy training_set_insert_own on nocendland.training_set
  for insert to authenticated with check ((select auth.uid()) = id_user);
create policy training_set_update_own on nocendland.training_set
  for update to authenticated
  using ((select auth.uid()) = id_user)
  with check ((select auth.uid()) = id_user);
create policy training_set_delete_own on nocendland.training_set
  for delete to authenticated using ((select auth.uid()) = id_user);

create policy training_share_select_own on nocendland.training_share
  for select to authenticated using ((select auth.uid()) = owner_id);

revoke all on all tables in schema nocendland from public, anon, authenticated, service_role;
revoke all on all sequences in schema nocendland from public, anon, authenticated, service_role;

grant select, insert, update on nocendland."user" to authenticated;
grant select, insert, update, delete on
  nocendland.nutrition_ingredient,
  nocendland.nutrition_intake,
  nocendland.nutrition_objective,
  nocendland.training_exercise,
  nocendland.training_schedule,
  nocendland.training_schedule_item,
  nocendland.training_entry,
  nocendland.training_set
to authenticated;
grant select on
  nocendland.nutrition_intake_with_totals,
  nocendland.nutrition_objectives_totals,
  nocendland.training_share
to authenticated;
grant usage on sequence
  nocendland.nutrition_ingredient_id_seq,
  nocendland.nutrition_intake_id_seq,
  nocendland.training_exercise_id_seq,
  nocendland.training_schedule_id_seq,
  nocendland.training_schedule_item_id_seq,
  nocendland.training_entry_id_seq,
  nocendland.training_set_id_seq
to authenticated;

grant select, insert, update, delete on
  nocendland."user",
  nocendland.nutrition_ingredient,
  nocendland.nutrition_intake,
  nocendland.nutrition_objective,
  nocendland.nutrition_objetive_level,
  nocendland.training_exercise,
  nocendland.training_share,
  nocendland.training_schedule,
  nocendland.training_schedule_item,
  nocendland.training_entry,
  nocendland.training_set
to service_role;
grant select on
  nocendland.nutrition_intake_with_totals,
  nocendland.nutrition_objectives_totals
to service_role;
grant usage, select, update on all sequences in schema nocendland to service_role;

create or replace function nocendland.ensure_training_schedule()
returns nocendland.training_schedule
language plpgsql
security invoker
set search_path = ''
as $$
declare
  result nocendland.training_schedule;
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'authentication_required';
  end if;

  select * into result
  from nocendland.training_schedule
  where id_user = current_user_id
  order by is_active desc, created_at, id
  limit 1;

  if result.id is null then
    insert into nocendland.training_schedule (id_user, name, is_active)
    values (current_user_id, 'Horario 1', true)
    returning * into result;
  end if;

  return result;
exception
  when unique_violation then
    select * into result
    from nocendland.training_schedule
    where id_user = current_user_id
    order by is_active desc, created_at, id
    limit 1;
    return result;
end;
$$;

create or replace function nocendland.activate_training_schedule(target_schedule_id bigint)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'authentication_required';
  end if;

  if not exists (
    select 1 from nocendland.training_schedule
    where id = target_schedule_id and id_user = current_user_id
  ) then
    raise exception 'schedule_not_found';
  end if;

  update nocendland.training_schedule
  set is_active = false, updated_at = now()
  where id_user = current_user_id and is_active;

  update nocendland.training_schedule
  set is_active = true, updated_at = now()
  where id = target_schedule_id and id_user = current_user_id;
end;
$$;

create or replace function nocendland_private.enforce_training_active_schedule()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  affected_user_id uuid := coalesce(new.id_user, old.id_user);
begin
  -- Durante el borrado en cascada de un usuario ya no hay un catálogo que proteger.
  if not exists (select 1 from nocendland."user" where id = affected_user_id) then
    return null;
  end if;

  if exists (select 1 from nocendland.training_schedule where id_user = affected_user_id)
    and not exists (
      select 1
      from nocendland.training_schedule
      where id_user = affected_user_id and is_active
    ) then
    raise exception 'active_schedule_required';
  end if;

  return null;
end;
$$;

create constraint trigger training_schedule_requires_active
after insert or update or delete on nocendland.training_schedule
deferrable initially deferred
for each row execute function nocendland_private.enforce_training_active_schedule();

create or replace function nocendland.import_training_share_manifest(
  shared_manifest jsonb,
  conflict_actions jsonb default '{}'::jsonb,
  activate_schedule boolean default false,
  source_share uuid default null
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  shared_exercise jsonb;
  shared_day jsonb;
  shared_item jsonb;
  shared_portable_id uuid;
  local_exercise_id bigint;
  local_schedule_id bigint;
  local_schedule_name text;
  base_schedule_name text;
  name_suffix integer := 1;
  exercise_mapping jsonb := '{}'::jsonb;
  action text;
begin
  if current_user_id is null then
    raise exception 'authentication_required';
  end if;

  if shared_manifest ->> 'version' <> 'training-share/v1'
    or shared_manifest ->> 'type' not in ('exercises', 'schedule')
    or jsonb_typeof(shared_manifest -> 'exercises') <> 'array' then
    raise exception 'invalid_training_share_manifest';
  end if;

  perform nocendland.ensure_training_schedule();

  for shared_exercise in
    select value from jsonb_array_elements(shared_manifest -> 'exercises')
  loop
    shared_portable_id := (shared_exercise ->> 'portableId')::uuid;
    action := coalesce(conflict_actions ->> shared_portable_id::text, 'keep');

    if action not in ('keep', 'update') then
      raise exception 'invalid_conflict_action';
    end if;

    select id into local_exercise_id
    from nocendland.training_exercise
    where id_user = current_user_id and portable_id = shared_portable_id;

    if local_exercise_id is null then
      insert into nocendland.training_exercise (
        id_user,
        portable_id,
        name,
        description,
        tips,
        image_path,
        video_url,
        training_modalities,
        muscle_groups,
        movement_patterns
      ) values (
        current_user_id,
        shared_portable_id,
        btrim(shared_exercise ->> 'name'),
        nullif(btrim(coalesce(shared_exercise ->> 'description', '')), ''),
        coalesce(array(select jsonb_array_elements_text(shared_exercise -> 'tips')), '{}'::text[]),
        null,
        nullif(btrim(coalesce(shared_exercise ->> 'videoUrl', '')), ''),
        coalesce(array(select jsonb_array_elements_text(coalesce(shared_exercise -> 'trainingModalities', '[]'::jsonb))), '{}'::text[]),
        coalesce(array(select jsonb_array_elements_text(coalesce(shared_exercise -> 'muscleGroups', '[]'::jsonb))), '{}'::text[]),
        coalesce(array(select jsonb_array_elements_text(coalesce(shared_exercise -> 'movementPatterns', '[]'::jsonb))), '{}'::text[])
      ) returning id into local_exercise_id;
    elsif action = 'update' then
      update nocendland.training_exercise
      set name = btrim(shared_exercise ->> 'name'),
          description = nullif(btrim(coalesce(shared_exercise ->> 'description', '')), ''),
          tips = coalesce(array(select jsonb_array_elements_text(shared_exercise -> 'tips')), '{}'::text[]),
          video_url = nullif(btrim(coalesce(shared_exercise ->> 'videoUrl', '')), ''),
          training_modalities = coalesce(array(select jsonb_array_elements_text(coalesce(shared_exercise -> 'trainingModalities', '[]'::jsonb))), '{}'::text[]),
          muscle_groups = coalesce(array(select jsonb_array_elements_text(coalesce(shared_exercise -> 'muscleGroups', '[]'::jsonb))), '{}'::text[]),
          movement_patterns = coalesce(array(select jsonb_array_elements_text(coalesce(shared_exercise -> 'movementPatterns', '[]'::jsonb))), '{}'::text[]),
          archived_at = null,
          updated_at = now()
      where id = local_exercise_id and id_user = current_user_id;
    end if;

    exercise_mapping := exercise_mapping
      || jsonb_build_object(shared_portable_id::text, local_exercise_id);
  end loop;

  if shared_manifest ->> 'type' = 'schedule' then
    if jsonb_typeof(shared_manifest -> 'schedule') <> 'object'
      or jsonb_typeof(shared_manifest -> 'schedule' -> 'days') <> 'array' then
      raise exception 'invalid_training_schedule_manifest';
    end if;

    shared_portable_id := (shared_manifest -> 'schedule' ->> 'portableId')::uuid;
    if exists (
      select 1 from nocendland.training_schedule
      where id_user = current_user_id and portable_id = shared_portable_id
    ) then
      raise exception 'schedule_already_imported';
    end if;

    base_schedule_name := btrim(shared_manifest -> 'schedule' ->> 'name');
    local_schedule_name := base_schedule_name;
    while exists (
      select 1 from nocendland.training_schedule
      where id_user = current_user_id and lower(btrim(name)) = lower(local_schedule_name)
    ) loop
      name_suffix := name_suffix + 1;
      local_schedule_name := base_schedule_name || ' (' || name_suffix || ')';
    end loop;

    if activate_schedule then
      update nocendland.training_schedule
      set is_active = false, updated_at = now()
      where id_user = current_user_id and is_active;
    end if;

    insert into nocendland.training_schedule (
      id_user, portable_id, name, is_active, source_share_id
    ) values (
      current_user_id, shared_portable_id, local_schedule_name, activate_schedule, source_share
    ) returning id into local_schedule_id;

    for shared_day in
      select value from jsonb_array_elements(shared_manifest -> 'schedule' -> 'days')
    loop
      if (shared_day ->> 'weekday')::integer not between 1 and 7
        or jsonb_typeof(shared_day -> 'items') <> 'array' then
        raise exception 'invalid_training_schedule_day';
      end if;

      for shared_item in
        select value from jsonb_array_elements(shared_day -> 'items')
      loop
        local_exercise_id :=
          (exercise_mapping ->> (shared_item ->> 'exercisePortableId'))::bigint;
        if local_exercise_id is null then
          raise exception 'missing_training_schedule_exercise';
        end if;

        insert into nocendland.training_schedule_item (
          id_user, schedule_id, exercise_id, weekday, set_count,
          target_repetitions, target_weight_kg, sort_order
        ) values (
          current_user_id,
          local_schedule_id,
          local_exercise_id,
          (shared_day ->> 'weekday')::smallint,
          (shared_item ->> 'setCount')::smallint,
          nullif(shared_item ->> 'targetRepetitions', '')::smallint,
          nullif(shared_item ->> 'targetWeightKg', '')::numeric,
          (shared_item ->> 'sortOrder')::integer
        );
      end loop;
    end loop;
  end if;

  return jsonb_build_object(
    'exerciseIds', exercise_mapping,
    'scheduleId', local_schedule_id,
    'scheduleName', local_schedule_name
  );
end;
$$;

create or replace function nocendland.save_training_schedule_catalog(
  catalog_draft jsonb,
  selected_key text
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  draft_item jsonb;
  created_schedule_id bigint;
  active_schedule_id bigint;
  selected_schedule_id bigint;
  schedule_ids jsonb := '{}'::jsonb;
begin
  if current_user_id is null then
    raise exception 'authentication_required';
  end if;

  if jsonb_typeof(catalog_draft) <> 'array'
    or jsonb_array_length(catalog_draft) = 0 then
    raise exception 'invalid_training_schedule_catalog';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(catalog_draft) item
    where nullif(btrim(item ->> 'key'), '') is null
      or (not coalesce((item ->> 'deleted')::boolean, false)
        and nullif(btrim(item ->> 'name'), '') is null)
      or ((item ->> 'id') is null and coalesce((item ->> 'deleted')::boolean, false))
      or ((item ->> 'id') is not null and (item ->> 'duplicateFromId') is not null)
  ) then
    raise exception 'invalid_training_schedule_catalog';
  end if;

  if (
    select count(*)
    from jsonb_array_elements(catalog_draft) item
    where not coalesce((item ->> 'deleted')::boolean, false)
  ) = 0 then
    raise exception 'training_schedule_required';
  end if;

  if (
    select count(*)
    from jsonb_array_elements(catalog_draft) item
    where not coalesce((item ->> 'deleted')::boolean, false)
      and coalesce((item ->> 'isActive')::boolean, false)
  ) <> 1 then
    raise exception 'single_active_training_schedule_required';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(catalog_draft) item
    group by item ->> 'key'
    having count(*) > 1
  ) or exists (
    select 1
    from jsonb_array_elements(catalog_draft) item
    where not coalesce((item ->> 'deleted')::boolean, false)
    group by lower(btrim(item ->> 'name'))
    having count(*) > 1
  ) then
    raise exception 'duplicate_training_schedule_catalog_value';
  end if;

  if not exists (
    select 1
    from jsonb_array_elements(catalog_draft) item
    where item ->> 'key' = selected_key
      and not coalesce((item ->> 'deleted')::boolean, false)
  ) then
    raise exception 'invalid_selected_training_schedule';
  end if;

  -- El conjunto completo y updated_at funcionan como control de concurrencia optimista.
  if exists (
    select 1
    from nocendland.training_schedule schedule
    where schedule.id_user = current_user_id
      and not exists (
        select 1 from jsonb_array_elements(catalog_draft) item
        where (item ->> 'id')::bigint = schedule.id
      )
  ) or exists (
    select 1
    from jsonb_array_elements(catalog_draft) item
    left join nocendland.training_schedule schedule
      on schedule.id = (item ->> 'id')::bigint
      and schedule.id_user = current_user_id
    where (item ->> 'id') is not null
      and (schedule.id is null
        or (item ->> 'updatedAt') is null
        or schedule.updated_at <> (item ->> 'updatedAt')::timestamptz)
  ) then
    raise exception 'stale_training_schedule_catalog';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(catalog_draft) item
    left join nocendland.training_schedule schedule
      on schedule.id = (item ->> 'duplicateFromId')::bigint
      and schedule.id_user = current_user_id
    where (item ->> 'duplicateFromId') is not null and schedule.id is null
  ) then
    raise exception 'invalid_training_schedule_duplicate';
  end if;

  -- Los nombres temporales permiten intercambiar nombres sin violar el índice único.
  update nocendland.training_schedule
  set name = '__catalog_' || gen_random_uuid()::text,
      is_active = false,
      updated_at = now()
  where id_user = current_user_id;

  for draft_item in select value from jsonb_array_elements(catalog_draft)
  loop
    if not coalesce((draft_item ->> 'deleted')::boolean, false)
      and (draft_item ->> 'id') is not null then
      update nocendland.training_schedule
      set name = btrim(draft_item ->> 'name'), updated_at = now()
      where id = (draft_item ->> 'id')::bigint and id_user = current_user_id;

      schedule_ids := schedule_ids || jsonb_build_object(
        draft_item ->> 'key',
        (draft_item ->> 'id')::bigint
      );
    end if;
  end loop;

  for draft_item in select value from jsonb_array_elements(catalog_draft)
  loop
    if (draft_item ->> 'id') is null then
      insert into nocendland.training_schedule (id_user, name, is_active)
      values (current_user_id, btrim(draft_item ->> 'name'), false)
      returning id into created_schedule_id;

      if (draft_item ->> 'duplicateFromId') is not null then
        insert into nocendland.training_schedule_item (
          id_user, schedule_id, exercise_id, weekday, set_count,
          target_repetitions, target_weight_kg, sort_order
        )
        select
          current_user_id, created_schedule_id, exercise_id, weekday, set_count,
          target_repetitions, target_weight_kg, sort_order
        from nocendland.training_schedule_item
        where id_user = current_user_id
          and schedule_id = (draft_item ->> 'duplicateFromId')::bigint;
      end if;

      schedule_ids := schedule_ids
        || jsonb_build_object(draft_item ->> 'key', created_schedule_id);
    end if;
  end loop;

  select (schedule_ids ->> (item ->> 'key'))::bigint into active_schedule_id
  from jsonb_array_elements(catalog_draft) item
  where not coalesce((item ->> 'deleted')::boolean, false)
    and coalesce((item ->> 'isActive')::boolean, false);

  update nocendland.training_schedule
  set is_active = true, updated_at = now()
  where id = active_schedule_id and id_user = current_user_id;

  delete from nocendland.training_schedule schedule
  using jsonb_array_elements(catalog_draft) item
  where coalesce((item ->> 'deleted')::boolean, false)
    and schedule.id = (item ->> 'id')::bigint
    and schedule.id_user = current_user_id;

  selected_schedule_id := (schedule_ids ->> selected_key)::bigint;
  return jsonb_build_object(
    'scheduleIds', schedule_ids,
    'selectedScheduleId', selected_schedule_id
  );
end;
$$;

revoke all on all functions in schema nocendland from public, anon, authenticated, service_role;
revoke all on all functions in schema nocendland_private from public, anon, authenticated, service_role;
grant execute on function nocendland.ensure_training_schedule() to authenticated, service_role;
grant execute on function nocendland.activate_training_schedule(bigint) to authenticated, service_role;
grant execute on function nocendland.import_training_share_manifest(jsonb, jsonb, boolean, uuid)
  to authenticated, service_role;
grant execute on function nocendland.save_training_schedule_catalog(jsonb, text)
  to authenticated, service_role;

create policy nocendland_select_own_objects
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'nocendland'
    and (
      (storage.foldername(name))[2] = (select auth.uid())::text
      or (
        (storage.foldername(name))[1] = 'nutrition_ingredient'
        and (storage.foldername(name))[2] = 'default'
      )
    )
  );

create policy nocendland_insert_own_objects
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'nocendland'
    and (storage.foldername(name))[2] = (select auth.uid())::text
  );

create policy nocendland_update_own_objects
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'nocendland'
    and (storage.foldername(name))[2] = (select auth.uid())::text
  )
  with check (
    bucket_id = 'nocendland'
    and (storage.foldername(name))[2] = (select auth.uid())::text
  );

create policy nocendland_delete_own_objects
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'nocendland'
    and (storage.foldername(name))[2] = (select auth.uid())::text
  );

alter role authenticator
  set pgrst.db_schemas = 'public, graphql_public, gift_card, nocendland';

notify pgrst, 'reload config';
notify pgrst, 'reload schema';

commit;
