create table nocendland.finance_settings (
  id_user uuid primary key
    references nocendland."user"(id) on update cascade on delete cascade,
  currency_code text not null default 'EUR',
  period_start_day smallint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint finance_settings_currency_code_check
    check (currency_code ~ '^[A-Z]{3}$'),
  constraint finance_settings_period_start_day_check
    check (period_start_day between 1 and 31)
);

create table nocendland.finance_category (
  id bigint generated by default as identity primary key,
  id_user uuid not null
    references nocendland."user"(id) on update cascade on delete cascade,
  name text not null,
  flow_type text not null,
  sort_order integer not null default 0,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint finance_category_id_owner_key unique (id, id_user),
  constraint finance_category_name_check check (btrim(name) <> ''),
  constraint finance_category_flow_type_check
    check (flow_type in ('income', 'expense', 'saving')),
  constraint finance_category_sort_order_check check (sort_order >= 0)
);

create unique index finance_category_owner_flow_name_key
  on nocendland.finance_category (id_user, flow_type, lower(btrim(name)));

create table nocendland.finance_period (
  id bigint generated by default as identity primary key,
  id_user uuid not null
    references nocendland."user"(id) on update cascade on delete cascade,
  starts_on date not null,
  ends_on date not null,
  opening_balance numeric(14, 2) not null default 0,
  status text not null default 'open',
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint finance_period_id_owner_key unique (id, id_user),
  constraint finance_period_owner_start_key unique (id_user, starts_on),
  constraint finance_period_dates_check check (ends_on >= starts_on),
  constraint finance_period_status_check check (status in ('open', 'closed')),
  constraint finance_period_closed_at_check check (
    (status = 'open' and closed_at is null)
    or (status = 'closed' and closed_at is not null)
  )
);

create table nocendland.finance_goal (
  id bigint generated by default as identity primary key,
  id_user uuid not null
    references nocendland."user"(id) on update cascade on delete cascade,
  name text not null,
  target_amount numeric(14, 2) not null,
  initial_amount numeric(14, 2) not null default 0,
  target_date date,
  status text not null default 'active',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint finance_goal_id_owner_key unique (id, id_user),
  constraint finance_goal_name_check check (btrim(name) <> ''),
  constraint finance_goal_target_amount_check check (target_amount > 0),
  constraint finance_goal_initial_amount_check check (initial_amount >= 0),
  constraint finance_goal_status_check
    check (status in ('active', 'completed', 'archived'))
);

create table nocendland.finance_recurring_item (
  id bigint generated by default as identity primary key,
  id_user uuid not null
    references nocendland."user"(id) on update cascade on delete cascade,
  category_id bigint not null,
  goal_id bigint,
  name text not null,
  amount numeric(14, 2) not null,
  starts_on date not null,
  ends_on date,
  due_day smallint not null,
  interval_months smallint not null default 1,
  archived_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint finance_recurring_item_id_owner_key unique (id, id_user),
  constraint finance_recurring_item_category_owner_fkey
    foreign key (category_id, id_user)
    references nocendland.finance_category(id, id_user) on delete restrict,
  constraint finance_recurring_item_goal_owner_fkey
    foreign key (goal_id, id_user)
    references nocendland.finance_goal(id, id_user) on delete restrict,
  constraint finance_recurring_item_name_check check (btrim(name) <> ''),
  constraint finance_recurring_item_amount_check check (amount > 0),
  constraint finance_recurring_item_dates_check
    check (ends_on is null or ends_on >= starts_on),
  constraint finance_recurring_item_due_day_check check (due_day between 1 and 31),
  constraint finance_recurring_item_interval_months_check
    check (interval_months between 1 and 120)
);

create table nocendland.finance_budget_allocation (
  id bigint generated by default as identity primary key,
  id_user uuid not null
    references nocendland."user"(id) on update cascade on delete cascade,
  period_id bigint not null,
  category_id bigint not null,
  planned_amount numeric(14, 2) not null default 0,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint finance_budget_allocation_id_owner_key unique (id, id_user),
  constraint finance_budget_allocation_period_owner_fkey
    foreign key (period_id, id_user)
    references nocendland.finance_period(id, id_user) on delete cascade,
  constraint finance_budget_allocation_category_owner_fkey
    foreign key (category_id, id_user)
    references nocendland.finance_category(id, id_user) on delete restrict,
  constraint finance_budget_allocation_owner_period_category_key
    unique (id_user, period_id, category_id),
  constraint finance_budget_allocation_planned_amount_check
    check (planned_amount >= 0)
);

create table nocendland.finance_movement (
  id bigint generated by default as identity primary key,
  id_user uuid not null
    references nocendland."user"(id) on update cascade on delete cascade,
  period_id bigint not null,
  category_id bigint not null,
  recurring_item_id bigint,
  goal_id bigint,
  name text not null,
  amount numeric(14, 2) not null,
  status text not null default 'pending',
  scheduled_on date not null,
  occurred_on date,
  recurrence_due_on date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint finance_movement_id_owner_key unique (id, id_user),
  constraint finance_movement_period_owner_fkey
    foreign key (period_id, id_user)
    references nocendland.finance_period(id, id_user) on delete cascade,
  constraint finance_movement_category_owner_fkey
    foreign key (category_id, id_user)
    references nocendland.finance_category(id, id_user) on delete restrict,
  constraint finance_movement_recurring_item_owner_fkey
    foreign key (recurring_item_id, id_user)
    references nocendland.finance_recurring_item(id, id_user) on delete restrict,
  constraint finance_movement_goal_owner_fkey
    foreign key (goal_id, id_user)
    references nocendland.finance_goal(id, id_user) on delete restrict,
  constraint finance_movement_name_check check (btrim(name) <> ''),
  constraint finance_movement_amount_check check (amount > 0),
  constraint finance_movement_status_check
    check (status in ('pending', 'completed', 'cancelled')),
  constraint finance_movement_occurred_on_check check (
    (status = 'completed' and occurred_on is not null)
    or (status <> 'completed' and occurred_on is null)
  ),
  constraint finance_movement_recurrence_check check (
    (recurring_item_id is null and recurrence_due_on is null)
    or (recurring_item_id is not null and recurrence_due_on is not null)
  )
);

create unique index finance_movement_recurring_occurrence_key
  on nocendland.finance_movement (id_user, recurring_item_id, recurrence_due_on)
  where recurring_item_id is not null;

create index finance_category_owner_active_idx
  on nocendland.finance_category (id_user, archived_at, sort_order, name);
create index finance_period_owner_dates_idx
  on nocendland.finance_period (id_user, starts_on desc, ends_on);
create index finance_goal_owner_status_idx
  on nocendland.finance_goal (id_user, status, target_date);
create index finance_recurring_item_owner_active_idx
  on nocendland.finance_recurring_item (id_user, archived_at, starts_on);
create index finance_recurring_item_category_owner_idx
  on nocendland.finance_recurring_item (category_id, id_user);
create index finance_recurring_item_goal_owner_idx
  on nocendland.finance_recurring_item (goal_id, id_user)
  where goal_id is not null;
create index finance_budget_allocation_period_owner_idx
  on nocendland.finance_budget_allocation (period_id, id_user);
create index finance_budget_allocation_category_owner_idx
  on nocendland.finance_budget_allocation (category_id, id_user);
create index finance_movement_owner_scheduled_idx
  on nocendland.finance_movement (id_user, scheduled_on desc, id desc);
create index finance_movement_period_status_idx
  on nocendland.finance_movement (period_id, id_user, status);
create index finance_movement_category_owner_idx
  on nocendland.finance_movement (category_id, id_user);
create index finance_movement_recurring_owner_idx
  on nocendland.finance_movement (recurring_item_id, id_user)
  where recurring_item_id is not null;
create index finance_movement_goal_owner_idx
  on nocendland.finance_movement (goal_id, id_user)
  where goal_id is not null;

create or replace function nocendland_private.set_finance_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

revoke execute on function nocendland_private.set_finance_updated_at() from public, anon, authenticated;

create trigger finance_settings_set_updated_at
before update on nocendland.finance_settings
for each row execute function nocendland_private.set_finance_updated_at();
create trigger finance_category_set_updated_at
before update on nocendland.finance_category
for each row execute function nocendland_private.set_finance_updated_at();
create trigger finance_period_set_updated_at
before update on nocendland.finance_period
for each row execute function nocendland_private.set_finance_updated_at();
create trigger finance_goal_set_updated_at
before update on nocendland.finance_goal
for each row execute function nocendland_private.set_finance_updated_at();
create trigger finance_recurring_item_set_updated_at
before update on nocendland.finance_recurring_item
for each row execute function nocendland_private.set_finance_updated_at();
create trigger finance_budget_allocation_set_updated_at
before update on nocendland.finance_budget_allocation
for each row execute function nocendland_private.set_finance_updated_at();
create trigger finance_movement_set_updated_at
before update on nocendland.finance_movement
for each row execute function nocendland_private.set_finance_updated_at();

alter table nocendland.finance_settings enable row level security;
alter table nocendland.finance_category enable row level security;
alter table nocendland.finance_period enable row level security;
alter table nocendland.finance_goal enable row level security;
alter table nocendland.finance_recurring_item enable row level security;
alter table nocendland.finance_budget_allocation enable row level security;
alter table nocendland.finance_movement enable row level security;

create policy finance_settings_select_own on nocendland.finance_settings
  for select to authenticated using ((select auth.uid()) = id_user);
create policy finance_settings_insert_own on nocendland.finance_settings
  for insert to authenticated with check ((select auth.uid()) = id_user);
create policy finance_settings_update_own on nocendland.finance_settings
  for update to authenticated
  using ((select auth.uid()) = id_user)
  with check ((select auth.uid()) = id_user);
create policy finance_settings_delete_own on nocendland.finance_settings
  for delete to authenticated using ((select auth.uid()) = id_user);

create policy finance_category_select_own on nocendland.finance_category
  for select to authenticated using ((select auth.uid()) = id_user);
create policy finance_category_insert_own on nocendland.finance_category
  for insert to authenticated with check ((select auth.uid()) = id_user);
create policy finance_category_update_own on nocendland.finance_category
  for update to authenticated
  using ((select auth.uid()) = id_user)
  with check ((select auth.uid()) = id_user);
create policy finance_category_delete_own on nocendland.finance_category
  for delete to authenticated using ((select auth.uid()) = id_user);

create policy finance_period_select_own on nocendland.finance_period
  for select to authenticated using ((select auth.uid()) = id_user);
create policy finance_period_insert_own on nocendland.finance_period
  for insert to authenticated with check ((select auth.uid()) = id_user);
create policy finance_period_update_own on nocendland.finance_period
  for update to authenticated
  using ((select auth.uid()) = id_user)
  with check ((select auth.uid()) = id_user);
create policy finance_period_delete_own on nocendland.finance_period
  for delete to authenticated using ((select auth.uid()) = id_user);

create policy finance_goal_select_own on nocendland.finance_goal
  for select to authenticated using ((select auth.uid()) = id_user);
create policy finance_goal_insert_own on nocendland.finance_goal
  for insert to authenticated with check ((select auth.uid()) = id_user);
create policy finance_goal_update_own on nocendland.finance_goal
  for update to authenticated
  using ((select auth.uid()) = id_user)
  with check ((select auth.uid()) = id_user);
create policy finance_goal_delete_own on nocendland.finance_goal
  for delete to authenticated using ((select auth.uid()) = id_user);

create policy finance_recurring_item_select_own on nocendland.finance_recurring_item
  for select to authenticated using ((select auth.uid()) = id_user);
create policy finance_recurring_item_insert_own on nocendland.finance_recurring_item
  for insert to authenticated with check ((select auth.uid()) = id_user);
create policy finance_recurring_item_update_own on nocendland.finance_recurring_item
  for update to authenticated
  using ((select auth.uid()) = id_user)
  with check ((select auth.uid()) = id_user);
create policy finance_recurring_item_delete_own on nocendland.finance_recurring_item
  for delete to authenticated using ((select auth.uid()) = id_user);

create policy finance_budget_allocation_select_own on nocendland.finance_budget_allocation
  for select to authenticated using ((select auth.uid()) = id_user);
create policy finance_budget_allocation_insert_own on nocendland.finance_budget_allocation
  for insert to authenticated with check ((select auth.uid()) = id_user);
create policy finance_budget_allocation_update_own on nocendland.finance_budget_allocation
  for update to authenticated
  using ((select auth.uid()) = id_user)
  with check ((select auth.uid()) = id_user);
create policy finance_budget_allocation_delete_own on nocendland.finance_budget_allocation
  for delete to authenticated using ((select auth.uid()) = id_user);

create policy finance_movement_select_own on nocendland.finance_movement
  for select to authenticated using ((select auth.uid()) = id_user);
create policy finance_movement_insert_own on nocendland.finance_movement
  for insert to authenticated with check ((select auth.uid()) = id_user);
create policy finance_movement_update_own on nocendland.finance_movement
  for update to authenticated
  using ((select auth.uid()) = id_user)
  with check ((select auth.uid()) = id_user);
create policy finance_movement_delete_own on nocendland.finance_movement
  for delete to authenticated using ((select auth.uid()) = id_user);

revoke all on
  nocendland.finance_settings,
  nocendland.finance_category,
  nocendland.finance_period,
  nocendland.finance_goal,
  nocendland.finance_recurring_item,
  nocendland.finance_budget_allocation,
  nocendland.finance_movement
from public, anon, authenticated, service_role;

grant select, insert, update, delete on
  nocendland.finance_settings,
  nocendland.finance_category,
  nocendland.finance_period,
  nocendland.finance_goal,
  nocendland.finance_recurring_item,
  nocendland.finance_budget_allocation,
  nocendland.finance_movement
to authenticated, service_role;

grant usage on sequence
  nocendland.finance_category_id_seq,
  nocendland.finance_period_id_seq,
  nocendland.finance_goal_id_seq,
  nocendland.finance_recurring_item_id_seq,
  nocendland.finance_budget_allocation_id_seq,
  nocendland.finance_movement_id_seq
to authenticated;

grant usage, select, update on sequence
  nocendland.finance_category_id_seq,
  nocendland.finance_period_id_seq,
  nocendland.finance_goal_id_seq,
  nocendland.finance_recurring_item_id_seq,
  nocendland.finance_budget_allocation_id_seq,
  nocendland.finance_movement_id_seq
to service_role;

create or replace function nocendland.ensure_finance_period(target_date date default current_date)
returns nocendland.finance_period
language plpgsql
security invoker
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  configured_start_day smallint;
  target_month date;
  previous_month date;
  next_month date;
  candidate_start date;
  candidate_end date;
  previous_end date;
  result nocendland.finance_period;
begin
  if current_user_id is null then
    raise exception 'authentication_required';
  end if;

  if target_date is null then
    raise exception 'target_date_required';
  end if;

  select * into result
  from nocendland.finance_period
  where id_user = current_user_id
    and target_date between starts_on and ends_on
  order by starts_on desc
  limit 1;

  if result.id is not null then
    return result;
  end if;

  insert into nocendland.finance_settings (id_user)
  values (current_user_id)
  on conflict (id_user) do nothing;

  insert into nocendland.finance_category (id_user, name, flow_type, sort_order)
  values
    (current_user_id, 'Nómina', 'income', 10),
    (current_user_id, 'Otros ingresos', 'income', 20),
    (current_user_id, 'Vivienda', 'expense', 30),
    (current_user_id, 'Alimentación', 'expense', 40),
    (current_user_id, 'Transporte', 'expense', 50),
    (current_user_id, 'Ocio', 'expense', 60),
    (current_user_id, 'Suscripciones', 'expense', 70),
    (current_user_id, 'Otros gastos', 'expense', 80),
    (current_user_id, 'Ahorro', 'saving', 90),
    (current_user_id, 'Inversión', 'saving', 100)
  on conflict do nothing;

  select period_start_day into configured_start_day
  from nocendland.finance_settings
  where id_user = current_user_id;

  target_month := date_trunc('month', target_date)::date;
  candidate_start := target_month + (
    least(
      configured_start_day::integer,
      extract(day from (target_month + interval '1 month - 1 day'))::integer
    ) - 1
  );

  if target_date < candidate_start then
    previous_month := (target_month - interval '1 month')::date;
    candidate_start := previous_month + (
      least(
        configured_start_day::integer,
        extract(day from (previous_month + interval '1 month - 1 day'))::integer
      ) - 1
    );
  end if;

  next_month := (date_trunc('month', candidate_start) + interval '1 month')::date;
  candidate_end := next_month + (
    least(
      configured_start_day::integer,
      extract(day from (next_month + interval '1 month - 1 day'))::integer
    ) - 1
  ) - 1;

  select max(ends_on) into previous_end
  from nocendland.finance_period
  where id_user = current_user_id
    and ends_on < target_date;

  if previous_end is not null and candidate_start <= previous_end then
    candidate_start := previous_end + 1;
  end if;

  insert into nocendland.finance_period (id_user, starts_on, ends_on)
  values (current_user_id, candidate_start, candidate_end)
  on conflict (id_user, starts_on) do nothing;

  select * into result
  from nocendland.finance_period
  where id_user = current_user_id
    and starts_on = candidate_start;

  with recurring_candidates as (
    select
      recurring.id,
      recurring.category_id,
      recurring.goal_id,
      recurring.name,
      recurring.amount,
      recurring.starts_on as recurring_starts_on,
      recurring.ends_on as recurring_ends_on,
      recurring.interval_months,
      generated_month.month_start::date as month_start,
      generated_month.month_start::date + (
        least(
          recurring.due_day::integer,
          extract(day from (generated_month.month_start + interval '1 month - 1 day'))::integer
        ) - 1
      ) as due_on,
      (
        extract(year from generated_month.month_start)::integer * 12
        + extract(month from generated_month.month_start)::integer
        - extract(year from date_trunc('month', recurring.starts_on))::integer * 12
        - extract(month from date_trunc('month', recurring.starts_on))::integer
      ) as month_distance
    from nocendland.finance_recurring_item recurring
    cross join lateral generate_series(
      date_trunc('month', result.starts_on)::date,
      date_trunc('month', result.ends_on)::date,
      interval '1 month'
    ) as generated_month(month_start)
    where recurring.id_user = current_user_id
      and recurring.archived_at is null
      and recurring.starts_on <= result.ends_on
      and (recurring.ends_on is null or recurring.ends_on >= result.starts_on)
  )
  insert into nocendland.finance_movement (
    id_user,
    period_id,
    category_id,
    recurring_item_id,
    goal_id,
    name,
    amount,
    status,
    scheduled_on,
    recurrence_due_on
  )
  select
    current_user_id,
    result.id,
    candidate.category_id,
    candidate.id,
    candidate.goal_id,
    candidate.name,
    candidate.amount,
    'pending',
    candidate.due_on,
    candidate.due_on
  from recurring_candidates candidate
  where candidate.month_distance >= 0
    and mod(candidate.month_distance, candidate.interval_months) = 0
    and candidate.due_on between result.starts_on and result.ends_on
    and candidate.due_on >= candidate.recurring_starts_on
    and (
      candidate.recurring_ends_on is null
      or candidate.due_on <= candidate.recurring_ends_on
    )
  on conflict do nothing;

  return result;
end;
$$;

revoke execute on function nocendland.ensure_finance_period(date) from public, anon;
grant execute on function nocendland.ensure_finance_period(date) to authenticated, service_role;
