begin;

alter table public.training_exercise
  add column portable_id uuid not null default gen_random_uuid();

alter table public.training_exercise
  add constraint training_exercise_owner_portable_key unique (id_user, portable_id);

create table public.training_schedule (
  id bigint generated by default as identity primary key,
  id_user uuid not null references public."user"(id) on delete cascade,
  portable_id uuid not null default gen_random_uuid(),
  name text not null,
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint training_schedule_name_check check (btrim(name) <> ''),
  constraint training_schedule_id_owner_key unique (id, id_user),
  constraint training_schedule_owner_portable_key unique (id_user, portable_id)
);

create unique index training_schedule_owner_name_key
  on public.training_schedule (id_user, lower(btrim(name)));

create unique index training_schedule_one_active_per_owner_key
  on public.training_schedule (id_user)
  where is_active;

alter table public.training_schedule enable row level security;

create policy training_schedule_select_own
  on public.training_schedule for select to authenticated
  using ((select auth.uid()) = id_user);

create policy training_schedule_insert_own
  on public.training_schedule for insert to authenticated
  with check ((select auth.uid()) = id_user);

create policy training_schedule_update_own
  on public.training_schedule for update to authenticated
  using ((select auth.uid()) = id_user)
  with check ((select auth.uid()) = id_user);

create policy training_schedule_delete_own
  on public.training_schedule for delete to authenticated
  using ((select auth.uid()) = id_user);

grant select, insert, update, delete on public.training_schedule to authenticated;
grant usage, select on sequence public.training_schedule_id_seq to authenticated;
revoke all on public.training_schedule from anon;

insert into public.training_schedule (id_user, name, is_active)
select id, 'Horario 1', true
from public."user";

alter table public.training_schedule_item
  add column schedule_id bigint;

update public.training_schedule_item item
set schedule_id = schedule.id
from public.training_schedule schedule
where schedule.id_user = item.id_user
  and schedule.is_active;

alter table public.training_schedule_item
  alter column schedule_id set not null;

alter table public.training_schedule_item
  add constraint training_schedule_item_schedule_owner_fkey
  foreign key (schedule_id, id_user)
  references public.training_schedule(id, id_user)
  on delete cascade;

alter table public.training_schedule_item
  drop constraint training_schedule_item_id_user_weekday_exercise_id_key;

alter table public.training_schedule_item
  add constraint training_schedule_item_schedule_weekday_exercise_key
  unique (schedule_id, weekday, exercise_id);

create index training_schedule_item_schedule_order_idx
  on public.training_schedule_item (schedule_id, weekday, sort_order);

create table public.training_share (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public."user"(id) on delete cascade,
  token_hash text not null unique,
  share_type text not null,
  title text not null,
  manifest jsonb not null,
  created_at timestamptz not null default now(),
  revoked_at timestamptz,
  constraint training_share_type_check check (share_type in ('exercises', 'schedule')),
  constraint training_share_title_check check (btrim(title) <> ''),
  constraint training_share_token_hash_check check (token_hash ~ '^[0-9a-f]{64}$'),
  constraint training_share_manifest_check check (
    manifest ->> 'version' = 'training-share/v1'
    and manifest ->> 'type' = share_type
    and jsonb_typeof(manifest -> 'exercises') = 'array'
  )
);

alter table public.training_share enable row level security;

create policy training_share_select_own
  on public.training_share for select to authenticated
  using ((select auth.uid()) = owner_id);

revoke all on public.training_share from anon, authenticated;
grant select on public.training_share to authenticated;

alter table public.training_schedule
  add column source_share_id uuid references public.training_share(id) on delete set null;

create index training_schedule_source_share_idx
  on public.training_schedule (id_user, source_share_id)
  where source_share_id is not null;

create or replace function public.ensure_training_schedule()
returns public.training_schedule
language plpgsql
security invoker
set search_path = ''
as $$
declare
  result public.training_schedule;
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'authentication_required';
  end if;

  select * into result
  from public.training_schedule
  where id_user = current_user_id
  order by is_active desc, created_at, id
  limit 1;

  if result.id is null then
    insert into public.training_schedule (id_user, name, is_active)
    values (current_user_id, 'Horario 1', true)
    returning * into result;
  end if;

  return result;
exception
  when unique_violation then
    select * into result
    from public.training_schedule
    where id_user = current_user_id
    order by is_active desc, created_at, id
    limit 1;
    return result;
end;
$$;

create or replace function public.activate_training_schedule(target_schedule_id bigint)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'authentication_required';
  end if;

  if not exists (
    select 1 from public.training_schedule
    where id = target_schedule_id and id_user = current_user_id
  ) then
    raise exception 'schedule_not_found';
  end if;

  update public.training_schedule
  set is_active = false, updated_at = now()
  where id_user = current_user_id and is_active;

  update public.training_schedule
  set is_active = true, updated_at = now()
  where id = target_schedule_id and id_user = current_user_id;
end;
$$;

create or replace function public.import_training_share_manifest(
  shared_manifest jsonb,
  conflict_actions jsonb default '{}'::jsonb,
  activate_schedule boolean default false,
  source_share uuid default null
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  shared_exercise jsonb;
  shared_day jsonb;
  shared_item jsonb;
  shared_portable_id uuid;
  local_exercise_id bigint;
  local_schedule_id bigint;
  local_schedule_name text;
  base_schedule_name text;
  name_suffix integer := 1;
  exercise_mapping jsonb := '{}'::jsonb;
  action text;
begin
  if current_user_id is null then
    raise exception 'authentication_required';
  end if;

  if shared_manifest ->> 'version' <> 'training-share/v1'
    or shared_manifest ->> 'type' not in ('exercises', 'schedule')
    or jsonb_typeof(shared_manifest -> 'exercises') <> 'array' then
    raise exception 'invalid_training_share_manifest';
  end if;

  perform public.ensure_training_schedule();

  for shared_exercise in
    select value from jsonb_array_elements(shared_manifest -> 'exercises')
  loop
    shared_portable_id := (shared_exercise ->> 'portableId')::uuid;
    action := coalesce(conflict_actions ->> shared_portable_id::text, 'keep');

    if action not in ('keep', 'update') then
      raise exception 'invalid_conflict_action';
    end if;

    select id into local_exercise_id
    from public.training_exercise
    where id_user = current_user_id and portable_id = shared_portable_id;

    if local_exercise_id is null then
      insert into public.training_exercise (
        id_user,
        portable_id,
        name,
        description,
        tips,
        image_path
      ) values (
        current_user_id,
        shared_portable_id,
        btrim(shared_exercise ->> 'name'),
        nullif(btrim(coalesce(shared_exercise ->> 'description', '')), ''),
        coalesce(array(select jsonb_array_elements_text(shared_exercise -> 'tips')), '{}'::text[]),
        null
      ) returning id into local_exercise_id;
    elsif action = 'update' then
      update public.training_exercise
      set name = btrim(shared_exercise ->> 'name'),
          description = nullif(btrim(coalesce(shared_exercise ->> 'description', '')), ''),
          tips = coalesce(array(select jsonb_array_elements_text(shared_exercise -> 'tips')), '{}'::text[]),
          archived_at = null,
          updated_at = now()
      where id = local_exercise_id and id_user = current_user_id;
    end if;

    exercise_mapping := exercise_mapping || jsonb_build_object(shared_portable_id::text, local_exercise_id);
  end loop;

  if shared_manifest ->> 'type' = 'schedule' then
    if jsonb_typeof(shared_manifest -> 'schedule') <> 'object'
      or jsonb_typeof(shared_manifest -> 'schedule' -> 'days') <> 'array' then
      raise exception 'invalid_training_schedule_manifest';
    end if;

    shared_portable_id := (shared_manifest -> 'schedule' ->> 'portableId')::uuid;
    if exists (
      select 1 from public.training_schedule
      where id_user = current_user_id and portable_id = shared_portable_id
    ) then
      raise exception 'schedule_already_imported';
    end if;

    base_schedule_name := btrim(shared_manifest -> 'schedule' ->> 'name');
    local_schedule_name := base_schedule_name;
    while exists (
      select 1 from public.training_schedule
      where id_user = current_user_id and lower(btrim(name)) = lower(local_schedule_name)
    ) loop
      name_suffix := name_suffix + 1;
      local_schedule_name := base_schedule_name || ' (' || name_suffix || ')';
    end loop;

    if activate_schedule then
      update public.training_schedule
      set is_active = false, updated_at = now()
      where id_user = current_user_id and is_active;
    end if;

    insert into public.training_schedule (
      id_user,
      portable_id,
      name,
      is_active,
      source_share_id
    ) values (
      current_user_id,
      shared_portable_id,
      local_schedule_name,
      activate_schedule,
      source_share
    ) returning id into local_schedule_id;

    for shared_day in
      select value from jsonb_array_elements(shared_manifest -> 'schedule' -> 'days')
    loop
      if (shared_day ->> 'weekday')::integer not between 1 and 7
        or jsonb_typeof(shared_day -> 'items') <> 'array' then
        raise exception 'invalid_training_schedule_day';
      end if;

      for shared_item in
        select value from jsonb_array_elements(shared_day -> 'items')
      loop
        local_exercise_id := (exercise_mapping ->> (shared_item ->> 'exercisePortableId'))::bigint;
        if local_exercise_id is null then
          raise exception 'missing_training_schedule_exercise';
        end if;

        insert into public.training_schedule_item (
          id_user,
          schedule_id,
          exercise_id,
          weekday,
          set_count,
          target_repetitions,
          target_weight_kg,
          sort_order
        ) values (
          current_user_id,
          local_schedule_id,
          local_exercise_id,
          (shared_day ->> 'weekday')::smallint,
          (shared_item ->> 'setCount')::smallint,
          nullif(shared_item ->> 'targetRepetitions', '')::smallint,
          nullif(shared_item ->> 'targetWeightKg', '')::numeric,
          (shared_item ->> 'sortOrder')::integer
        );
      end loop;
    end loop;
  end if;

  return jsonb_build_object(
    'exerciseIds', exercise_mapping,
    'scheduleId', local_schedule_id,
    'scheduleName', local_schedule_name
  );
end;
$$;

revoke all on function public.ensure_training_schedule() from public, anon;
revoke all on function public.activate_training_schedule(bigint) from public, anon;
revoke all on function public.import_training_share_manifest(jsonb, jsonb, boolean, uuid) from public, anon;
grant execute on function public.ensure_training_schedule() to authenticated;
grant execute on function public.activate_training_schedule(bigint) to authenticated;
grant execute on function public.import_training_share_manifest(jsonb, jsonb, boolean, uuid) to authenticated;

commit;
